# Select the base image that is best for our application
FROM python:3

ENV PYTHONUNBUFFERED 1

# Set the working directory to copy stuff to
WORKDIR /app

# Copy all the code from the local directory into the image

COPY requirements.txt requirements.txt


# Install any language dependencies
RUN pip install -r requirements.txt

# Set the command to run the application
CMD python attendees/account_info_consumer.py
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]
